// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvFROlsP3Dep8Bwzc2P9KlJcTcAz5YOM',
    appId: '1:107795036305:web:5b0c99ca118f1065706730',
    messagingSenderId: '107795036305',
    projectId: 'optimile-4de76',
    authDomain: 'optimile-4de76.firebaseapp.com',
    storageBucket: 'optimile-4de76.firebasestorage.app',
    measurementId: 'G-2FC678WJVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrcMg3r9sX5cS0f70MLW2Zvhh3QI4rW88',
    appId: '1:107795036305:android:312ddbac9ca0f73b706730',
    messagingSenderId: '107795036305',
    projectId: 'optimile-4de76',
    storageBucket: 'optimile-4de76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzKApMr1-oAFEXv-cH8rvIN6pYrj4Cs1E',
    appId: '1:107795036305:ios:8e6f5d11bd3c6863706730',
    messagingSenderId: '107795036305',
    projectId: 'optimile-4de76',
    storageBucket: 'optimile-4de76.firebasestorage.app',
    iosClientId: '107795036305-g8gt5iej0rndtmn9kjajton73aout75g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzKApMr1-oAFEXv-cH8rvIN6pYrj4Cs1E',
    appId: '1:107795036305:ios:8e6f5d11bd3c6863706730',
    messagingSenderId: '107795036305',
    projectId: 'optimile-4de76',
    storageBucket: 'optimile-4de76.firebasestorage.app',
    iosClientId: '107795036305-g8gt5iej0rndtmn9kjajton73aout75g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBvFROlsP3Dep8Bwzc2P9KlJcTcAz5YOM',
    appId: '1:107795036305:web:10a1bb0ddc7376dc706730',
    messagingSenderId: '107795036305',
    projectId: 'optimile-4de76',
    authDomain: 'optimile-4de76.firebaseapp.com',
    storageBucket: 'optimile-4de76.firebasestorage.app',
    measurementId: 'G-GN0006DCK2',
  );
}
